### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#146]
### Frontend
- [x] Finalize initial blocks
- [x] Go through list of know bugs from Jira
- [x] Renderer tests
- [ ] Tests for Actions
   
### Backend
- [x] Connection controller and test
- [x] Secrets
- [x] Sheets connector

### Hosting & CLI
- [ ] Deploy to Docker hub
- [ ] Lambda deploy
- [x] Deploy provider (Netlify / Vercel / Digital Ocean)
- [ ] Init Lowdefy project CLI
- [ ] Init Docker in CLI
- [ ] Init custom block CLI
- [x] CLI telemetry & CLI config flags

### Documentation
- [x] Update tutorial
- [x] All concepts
- [ ] New connections
- [ ] Main ReadMe
- [ ] Package ReadMes
- [ ] Example ReadMe
