### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#368]
#### Basic
- [x] Context
- [x] Box
- [x] DangerousHtml
- [x] Html
- [x] List
- [x] Span

#### Antd
- [x] Affix
- [x] Alert
- [x] Anchor
- [x] AutoComplete
- [x] Avatar
- [x] Badge
- [x] Breadcrumb
- [x] Button
- [x] ButtonSelector
- [x] Card
- [x] CheckboxSelector
- [x] Collapse
- [x] Comment
- [x] ConfirmModal
- [x] ControlledList
- [x] DateRangeSelector
- [x] DateSelector
- [x] DateTimeSelector
- [x] Descriptions
- [x] Divider
- [x] Drawer
- [x] Icon
- [x] Label
- [x] Menu
- [x] Message
- [x] MobileMenu
- [x] Modal
- [x] MonthSelector
- [x] MultipleSelector
- [x] Notification
- [x] NumberInput
- [x] PageHCF
- [x] PageHCSF
- [x] PageHeaderMenu
- [x] PageHSCF
- [x] PageSHCF
- [x] PageSiderMenu
- [x] Pagination
- [x] Paragraph
- [x] ParagraphInput
- [x] Progress
- [x] RadioSelector
- [x] RatingSlider
- [x] Result
- [x] S3UploadButton
- [x] Selector
- [x] Skeleton
- [x] Spin
- [x] Statistic
- [x] Switch
- [x] Tabs
- [x] TextArea
- [x] TextInput
- [x] Title
- [x] TitleInput
- [x] WeekSelector
- [ ] Timeline

#### AmCharts
- [x] AmCharts4Pie
- [x] AmCharts4XY

#### Color Selector
- [x] ColorSelector
- [x] ChromeColorSelector
- [x] TwitterColorSelector
- [x] GithubColorSelector
- [x] SwatchesColorSelector
- [x] SliderColorSelector
- [x] CompactColorSelector
- [x] CircleColorSelector

#### Markdown
- [x] DangerousMarkdown
- [x] Markdown
- [x] MarkdownWithCode

**Comment by Gervwyk** [comment]
#### Todo:
- [ ] _formatter operator.
- [ ] remove `open` From modal and Drawer.
- [ ] Overflow issue on code blocks.
- [ ] Context does not render with blocks template.
- [ ] Fix Statistic.
- [ ] Examples of progress dashboard and progress.
- [ ] Concept for Lists.
- [ ] contextId and urlQuery.  
- [ ] Sendgrid docs.
- [ ] Event object.
- [ ] Remove Skeleton for now.
- [ ] CircleColorSelector and SwatchesColorSelector does not render.
- [ ] MonthSelector suffix icon and default label.
- [ ] Next steps page.
- [ ] Footer and links in the header.
- [ ] Affix Sider collapse button and maybe set in global.
